import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Crown,ShoppingBag,Sparkles,ArrowRight,Check,ShieldCheck,Truck,Plus,Minus,X,Lock,Menu,Package,Layers,Boxes,Activity,BookOpen,Heart,Tag} from 'lucide-react';
import './styles.css';

const BRAND={name:'Loyalty Lane',promise:'Quality you can wear. Culture you can feel. Legacy you can build.',motto:'Loyalty is the language.',colors:['Black','Gold','Cream','Burgundy','Purple','White']};
const COLLECTIONS=[
 {id:'heritage',name:'1990s Catalogue Series',audience:'Heritage / Limited Drops',fulfillment:'Physical Inventory',desc:'Collectible 1990–1994 identity drops with jersey set, full outfit, catalogue page, QR story and limited packaging.'},
 {id:'core',name:'Loyalty Core Essentials',audience:'Everyday Premium',fulfillment:'Physical + POD',desc:'High-margin socks, underwear and essential silhouettes engineered for repeat rotation.'},
 {id:'gold',name:'Loyalty Gold Line',audience:'Accessories',fulfillment:'Physical Inventory',desc:'Chains, pendants, nameplates, rings, bracelets and dog tags for the Lane finish.'},
 {id:'bags',name:'Signature Book Bags',audience:'Accessories',fulfillment:'Physical Inventory',desc:'Royal Flush, King of Hearts, Ace of Spades and Legacy Wings carry systems.'},
 {id:'kottons',name:"Kotton’s Code",audience:'Youth Market',fulfillment:'Tapstitch POD',desc:'Bold youth streetwear, graphic-heavy styles and positive messaging.'},
 {id:'lingo',name:"That’s My Lingo",audience:'Adult / Lounge Aesthetic',fulfillment:'Tapstitch POD',desc:'Lounge-inspired fits and nightlife energy without turning the apparel store into a wagering product.'},
 {id:'events',name:'Events By The Lane',audience:'Event Exclusives',fulfillment:'Drop / Physical',desc:'Pop-up drops, event exclusives and limited editions tied to real-world Lane moments.'}
];
const PRODUCTS=[
 {id:'1991-jersey',collection:'heritage',name:'1991 Heritage Jersey',category:'1990s Catalogue',price:59.99,cost:18.5,stock:120,sizes:['S','M','L','XL','2XL'],badge:'Heritage Drop',material:'Premium jersey',vendor:'Loyalty Lane Bulk',desc:'Collectible foundation-year jersey from the 1990s catalogue system.'},
 {id:'tap-hoodie',collection:'core',name:'Loyalty Core Heavyweight Hoodie',category:'Core Essentials',price:85,cost:14.92,stock:0,sizes:['S','M','L','XL','2XL'],badge:'POD',material:'350 GSM fleece',vendor:'Tapstitch',desc:'Heavyweight everyday layer with the Lane identity and premium finish.'},
 {id:'loyalty-tee',collection:'core',name:'Stay Loyal Executive Tee',category:'Core Essentials',price:45,cost:9.99,stock:0,sizes:['S','M','L','XL','2XL'],badge:'POD',material:'Heavy cotton',vendor:'Tapstitch',desc:'Clean executive tee designed for the Loyalty Lane daily uniform.'},
 {id:'kottons-tee',collection:'kottons',name:"Kotton’s Code Oversized Tee",category:"Kotton’s Code",price:45,cost:9.99,stock:0,sizes:['S','M','L','XL','2XL'],badge:'Youth',material:'Snow washed cotton',vendor:'Tapstitch',desc:'Graphic-ready oversized youth silhouette built for the Kotton’s Code universe.'},
 {id:'lingo-sweat',collection:'lingo',name:"That’s My Lingo Contrast Sweatshirt",category:"That’s My Lingo",price:65,cost:19.99,stock:0,sizes:['S','M','L','XL','2XL'],badge:'Lingo',material:'Contrast fleece',vendor:'Tapstitch',desc:'Nightlife-inspired contrast sweatshirt for the That’s My Lingo world.'},
 {id:'socks-91',collection:'core',name:'91 Black Gold Rib Socks',category:'Socks',price:12,cost:2.1,stock:300,sizes:['OS'],badge:'Core',material:'Rib knit',vendor:'Loyalty Lane Bulk',desc:'Foundation-year black and gold rib sock pack.'},
 {id:'gold-chain',collection:'gold',name:'Loyalty Gold Rope Chain',category:'Gold Line',price:29.99,cost:6,stock:80,sizes:['24in','26in'],badge:'Gold Line',material:'Gold-plated brass',vendor:'Loyalty Lane Bulk',desc:'Statement accessory for the Loyalty Gold Line.'},
 {id:'book-bag',collection:'bags',name:'Royal Flush Signature Book Bag',category:'Book Bags',price:49.99,cost:12,stock:60,sizes:['OS'],badge:'Signature',material:'Structured textile',vendor:'Loyalty Lane Bulk',desc:'Signature carry piece built around the heritage catalogue aesthetic.'}
];
const SUPPLY=[['Apparel / Jerseys','China','50–100','20–30 days'],['Socks','USA / China','100–300 pairs','15–25 days'],['Underwear','USA / China','50–200','15–30 days'],['Bags / Backpacks','China / UK','100+','20–30 days'],['Jewelry','China','30–100','10–20 days'],['Footwear OEM','China','100–500','30–45 days'],['Packaging','USA / China','100–500','10–20 days']];
const VENDORS=[['Tapstitch POD','Immediate cash-flow line','Tees • Hoodies • Track Jackets • Loungewear'],['Shopify Commerce','Catalog + checkout authority','Products • Collections • Orders • Customer checkout'],['Loyalty Lane Bulk','Physical drop inventory','1990s Series • Gold Line • Bags • Socks • Underwear'],['Lingo Legacy','Identity + loyalty layer','Lingo ID • Rewards • XP • analytics • reinvestment']];
const MOTTO='STAY LOYAL TO YOUR OWN LANE.';
function App(){
 const [tab,setTab]=useState('home'); const [cart,setCart]=useState([]); const [selected,setSelected]=useState(PRODUCTS[0]); const [menu,setMenu]=useState(false); const [notice,setNotice]=useState(''); const [collection,setCollection]=useState('all');
 const visible=useMemo(()=>collection==='all'?PRODUCTS:PRODUCTS.filter(p=>p.collection===collection),[collection]);
 const total=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.qty,0),[cart]); const count=useMemo(()=>cart.reduce((s,i)=>s+i.qty,0),[cart]);
 const add=(p,size=p.sizes[0])=>{setCart(c=>{const key=p.id+'-'+size;const found=c.find(i=>i.key===key);return found?c.map(i=>i.key===key?{...i,qty:i.qty+1}:i):[...c,{key,id:p.id,name:p.name,size,price:p.price,qty:1,vendor:p.vendor}]});setNotice('Added to your Lane cart.');};
 const qty=(key,d)=>setCart(c=>c.flatMap(i=>i.key===key?[{...i,qty:i.qty+d}].filter(x=>x.qty>0):[i]));
 const checkout=()=>setNotice('Checkout handoff is ready for the configured Shopify commerce provider. No payment is processed by this client shell.');
 const nav=(id)=>{setTab(id);setMenu(false)};
 return <div className="app">
  <div className="topline"><span><Sparkles size={13}/> LOYALTY LANE APPAREL™</span><span className="desktop">{BRAND.promise}</span></div>
  <header><button className="icon mobile" onClick={()=>setMenu(!menu)} aria-label="Open menu"><Menu/></button><button className="brand" onClick={()=>nav('home')}><span className="brandmark"><Crown size={21}/></span><span><b>LOYALTY LANE</b><small>APPAREL™ • TAP STITCH • SHOPIFY</small></span></button><nav className={menu?'open':''}>{[['home','Home'],['shop','Shop'],['collections','Collections'],['lookbook','Lookbook'],['operations','Operations'],['rewards','Loyalty']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>nav(id)} key={id}>{label}</button>)}</nav><button className="cartbtn" onClick={()=>nav('cart')} aria-label="Open cart"><ShoppingBag size={19}/>{count>0&&<em>{count}</em>}</button></header>
  {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={15}/></button></div>}
  {tab==='home'&&<main><section className="hero"><div className="hero-copy"><span className="eyebrow">ONE BRAND • ONE CATALOG • ONE COMMERCE LAYER</span><h1>WEAR THE<br/><strong>LEGACY.</strong></h1><p>{BRAND.promise}</p><p className="fine">{BRAND.motto} • We design it. Source it. Brand it. Track it. Sell it. Reinvest it.</p><div className="actions"><button className="primary" onClick={()=>nav('shop')}>ENTER THE LANE <ArrowRight size={17}/></button><button className="secondary" onClick={()=>nav('collections')}>VIEW ECOSYSTEM</button></div></div><div className="hero-card"><div className="glow"></div><Crown size={70} strokeWidth={1}/><span>LOYALTY LANE</span><b>STAY LOYAL.</b></div></section><section className="motto"><ShieldCheck size={18}/><span>{MOTTO}</span></section><section className="grid four">{COLLECTIONS.slice(0,4).map(c=><button className="card compact" key={c.id} onClick={()=>{setCollection(c.id);nav('shop')}}><Layers size={25}/><span className="eyebrow">{c.fulfillment}</span><h3>{c.name}</h3><p>{c.desc}</p></button>)}</section></main>}
  {tab==='shop'&&<main className="page"><div className="pagehead"><span className="eyebrow">SHOPIFY CATALOG • TAPSTITCH + PHYSICAL DROPS</span><h2>THE LANE, CONSOLIDATED.</h2><p>One storefront catalog. Fulfillment is routed by authoritative vendor mapping; client UI never invents inventory, payment, or order success.</p></div><div className="filterbar"><button className={collection==='all'?'active':''} onClick={()=>setCollection('all')}>All</button>{COLLECTIONS.map(c=><button className={collection===c.id?'active':''} onClick={()=>setCollection(c.id)} key={c.id}>{c.name}</button>)}</div><div className="grid">{visible.map(p=><ProductCard key={p.id} p={p} onAdd={add} onSelect={setSelected}/>)}</div><ProductDetail p={selected} onAdd={add}/></main>}
  {tab==='collections'&&<main className="page"><div className="pagehead"><span className="eyebrow">ECOSYSTEM ARCHITECTURE</span><h2>EVERY LANE. ONE STOREFRONT.</h2><p>All apparel, accessories, youth, lounge and event merchandise are organized under one Loyalty Lane commerce front.</p></div><div className="grid">{COLLECTIONS.map(c=><article className="card" key={c.id}><div className="visual"><Layers size={44}/><span>{c.fulfillment}</span></div><div className="cardbody"><span>{c.audience}</span><h3>{c.name}</h3><p>{c.desc}</p><button className="smallbtn" onClick={()=>{setCollection(c.id);nav('shop')}}>SHOP COLLECTION <ArrowRight size={14}/></button></div></article>)}</div></main>}
  {tab==='lookbook'&&<main className="page"><div className="look"><div><span className="eyebrow">EDITORIAL / 1990–1994 → 2026</span><h2>HERITAGE CATALOGUE<br/><strong>STUDIO SERIES</strong></h2><p>Every heritage drop can carry its jersey set, full outfit, catalogue/poster page, QR story and limited packaging.</p><button className="primary" onClick={()=>{setCollection('heritage');nav('shop')}}>SHOP HERITAGE <ArrowRight size={17}/></button></div><div className="editorial"><span>01</span><b>FOUNDATION<br/>IDENTITY</b></div></div></main>}
  {tab==='operations'&&<main className="page"><div className="pagehead"><span className="eyebrow">SUPPLY CHAIN • MARGIN • FULFILLMENT</span><h2>COMMERCE CONTROL ROOM.</h2><p>Capital discipline stays ahead of inventory. Samples first, low MOQ, escrow/trade assurance for bulk runs, pre-orders where appropriate, and unit-level cost tracking.</p></div><section className="panel"><div className="statusrow"><span>FULFILLMENT SPLIT</span><b>SHOPIFY → TAPSTITCH / BULK</b></div><div className="grid four">{VENDORS.map(v=><div className="card compact" key={v[0]}><Boxes size={24}/><h3>{v[0]}</h3><span>{v[1]}</span><p>{v[2]}</p></div>)}</div></section><section className="panel"><h3>SUPPLIER PIPELINE</h3><div className="table">{SUPPLY.map((r,i)=><div className="tr" key={i}><span>{r[0]}</span><span>{r[1]}</span><span>MOQ {r[2]}</span><span>{r[3]}</span></div>)}</div></section><section className="panel"><h3>OPERATING GATES</h3><div className="grid four">{['Sample approval before bulk order','Escrow / Trade Assurance for supplier runs','Pre-order limited drops to protect cash flow','Track every cost, unit, vendor and fulfillment state'].map(x=><div className="card compact" key={x}><Check size={22}/><p>{x}</p></div>)}</div></section></main>}
  {tab==='rewards'&&<main className="page narrow"><div className="panel"><ShieldCheck size={35}/><span className="eyebrow">LINGO ID / REWARDS</span><h2>YOUR LANE STATUS</h2><p>Connect Lingo ID to load authoritative member status, rewards, XP and eligible offers. This shell never fabricates account state.</p><div className="statusrow"><span>ACCOUNT STATE</span><b>AUTHENTICATION REQUIRED</b></div><button className="primary" onClick={()=>setNotice('Lingo ID handoff is not configured in this repository yet.')}>CONNECT LINGO ID <ArrowRight size={17}/></button></div></main>}
  {tab==='cart'&&<main className="page narrow"><div className="pagehead"><span className="eyebrow">CART / SHOPIFY CHECKOUT HANDOFF</span><h2>YOUR LANE CART.</h2></div>{cart.length===0?<div className="empty"><ShoppingBag size={42}/><p>Your cart is empty.</p><button className="primary" onClick={()=>nav('shop')}>BROWSE THE LANE</button></div>:<div className="cartpanel">{cart.map(i=><div className="cartitem" key={i.key}><div><b>{i.name}</b><small>{i.vendor} • Size {i.size} • ${i.price.toFixed(2)}</small></div><div className="stepper"><button onClick={()=>qty(i.key,-1)} aria-label="Decrease"><Minus size={14}/></button><b>{i.qty}</b><button onClick={()=>qty(i.key,1)} aria-label="Increase"><Plus size={14}/></button></div></div>)}<div className="total"><span>Subtotal</span><b>${total.toFixed(2)}</b></div><button className="primary full" onClick={checkout}><Lock size={16}/> CONTINUE TO SHOPIFY</button><p className="fine"><Truck size={13}/> Payment and fulfillment are handled by configured commerce services. No raw card/CVC collection occurs in this client shell.</p></div>}</main>}
  <footer><span>LOYALTY LANE APPAREL™</span><span>Tap Stitch • Shopify • Lingo Legacy</span><span className="desktop">{BRAND.motto}</span></footer>
 </div>}
function ProductCard({p,onAdd,onSelect}){return <article className="card"><button className="visual" onClick={()=>onSelect(p)} aria-label={'View '+p.name}><span>{p.badge}</span><Crown size={44}/><small>{p.vendor} • {p.material}</small></button><div className="cardbody"><span>{p.category}</span><h3>{p.name}</h3><p>{p.desc}</p><div className="cardfoot"><div><b>${p.price.toFixed(2)}</b><small> Cost basis ${p.cost.toFixed(2)}</small></div><button className="smallbtn" onClick={()=>onAdd(p)} disabled={p.stock===0&&p.vendor!=='Tapstitch'}>{p.stock===0&&p.vendor!=='Tapstitch'?'SOLD OUT':'ADD'} <Plus size={14}/></button></div></div></article>}
function ProductDetail({p,onAdd}){return <section className="detail"><div className="detailvisual"><Crown size={75}/></div><div><span className="eyebrow">PRODUCT DETAIL • {p.vendor}</span><h2>{p.name}</h2><p>{p.desc}</p><p className="fine">Fulfillment: {p.vendor} • Stock state is illustrative until connected to authoritative inventory.</p><div className="sizes">{p.sizes.map(s=><button key={s} onClick={()=>onAdd(p,s)}>{s}</button>)}</div><button className="primary" onClick={()=>onAdd(p)}>ADD TO CART • ${p.price.toFixed(2)}</button></div></section>}
createRoot(document.getElementById('root')).render(<App/>);