import React,{useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Crown,ShoppingBag,Sparkles,ArrowRight,Check,ShieldCheck,Truck,Plus,Minus,X,Lock,Menu,UserCheck} from 'lucide-react';
import './styles.css';

const PRODUCTS=[
{id:'tap-hoodie',name:'Tap Stitch Heavyweight Hoodie',category:'Outerwear',price:78,sizes:['S','M','L','XL','2XL'],badge:'Signature',material:'Heavyweight cotton',desc:'A premium Shadow Noir staple built around the Tap Stitch identity.'},
{id:'loyalty-tee',name:'Stay Loyal Executive Tee',category:'Essentials',price:42,sizes:['S','M','L','XL','2XL'],badge:'Core',material:'Premium jersey',desc:'Clean front, executive finish, and an understated Loyalty Lane mark.'},
{id:'lane-cap',name:'Loyalty Lane Structured Cap',category:'Headwear',price:34,sizes:['OS'],badge:'Limited',material:'Structured twill',desc:'Low-profile streetwear hardware with restrained metallic detailing.'},
{id:'studio-jacket',name:'Shadow Noir Studio Jacket',category:'Outerwear',price:96,sizes:['M','L','XL','2XL'],badge:'Studio',material:'Technical shell',desc:'Cinematic utility layer for the next Loyalty Lane campaign.'}
];
const MOTTO='STAY LOYAL TO YOUR OWN LANE.';
function App(){
 const [tab,setTab]=useState('shop'); const [cart,setCart]=useState([]); const [selected,setSelected]=useState(PRODUCTS[0]); const [menu,setMenu]=useState(false); const [notice,setNotice]=useState('');
 const total=useMemo(()=>cart.reduce((s,i)=>s+i.price*i.qty,0),[cart]); const count=useMemo(()=>cart.reduce((s,i)=>s+i.qty,0),[cart]);
 const add=(p,size=p.sizes[0])=>{setCart(c=>{const key=p.id+'-'+size; const found=c.find(i=>i.key===key); return found?c.map(i=>i.key===key?{...i,qty:i.qty+1}:i):[...c,{key,id:p.id,name:p.name,size,price:p.price,qty:1}]}); setNotice('Added to your Lane cart.');};
 const qty=(key,d)=>setCart(c=>c.flatMap(i=>i.key===key?[{...i,qty:i.qty+d}].filter(x=>x.qty>0):[i]));
 const handoff=()=>setNotice('Checkout handoff is ready for the configured commerce provider. No payment was processed in this demo shell.');
 return <div className="app">
  <div className="topline"><span><Sparkles size={13}/> TAP STITCH / LOYALTY LANE</span><span className="desktop">ONE SHELL • ONE LANE • STAY LOYAL.</span></div>
  <header><button className="icon mobile" onClick={()=>setMenu(!menu)} aria-label="Open menu"><Menu/></button><button className="brand" onClick={()=>setTab('home')}><span className="brandmark"><Crown size={21}/></span><span><b>LOYALTY LANE</b><small>APPAREL™ • TAP STITCH</small></span></button><nav className={menu?'open':''}>{[['home','Home'],['shop','Shop'],['lookbook','Lookbook'],['rewards','Loyalty']].map(([id,label])=><button className={tab===id?'active':''} onClick={()=>{setTab(id);setMenu(false)}} key={id}>{label}</button>)}</nav><button className="cartbtn" onClick={()=>setTab('cart')} aria-label="Open cart"><ShoppingBag size={19}/>{count>0&&<em>{count}</em>}</button></header>
  {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss"><X size={15}/></button></div>}
  {tab==='home'&&<main><section className="hero"><div className="hero-copy"><span className="eyebrow">SHADOW NOIR / STUDIO PRODUCTION FRONT</span><h1>WEAR THE<br/><strong>LEGACY.</strong></h1><p>Premium streetwear, Tap Stitch identity, and loyalty-driven commerce in one cohesive Lane.</p><div className="actions"><button className="primary" onClick={()=>setTab('shop')}>ENTER THE LANE <ArrowRight size={17}/></button><button className="secondary" onClick={()=>setTab('lookbook')}>VIEW LOOKBOOK</button></div></div><div className="hero-card"><div className="glow"></div><Crown size={70} strokeWidth={1}/><span>TAP STITCH</span><b>STAY LOYAL.</b></div></section><section className="motto"><ShieldCheck size={18}/><span>{MOTTO}</span></section><ProductStrip onAdd={add} onSelect={setSelected}/></main>}
  {tab==='shop'&&<main className="page"><div className="pagehead"><span className="eyebrow">CATALOG / DROP 01</span><h2>THE LANE, CURATED.</h2><p>Built for everyday rotation. Actual inventory and fulfillment remain backend-controlled.</p></div><div className="grid">{PRODUCTS.map(p=><ProductCard key={p.id} p={p} onAdd={add} onSelect={setSelected}/>)}</div><ProductDetail p={selected} onAdd={add}/></main>}
  {tab==='lookbook'&&<main className="page"><div className="look"><div><span className="eyebrow">EDITORIAL / 2026</span><h2>SHADOW NOIR<br/><strong>STUDIO SERIES</strong></h2><p>A campaign-ready visual world for collections, drops, stories, and short-form fashion media.</p><button className="primary" onClick={()=>setTab('shop')}>SHOP THE SERIES <ArrowRight size={17}/></button></div><div className="editorial"><span>01</span><b>ARCHITECTURAL<br/>UTILITY</b></div></div></main>}
  {tab==='rewards'&&<main className="page narrow"><div className="panel"><ShieldCheck size={35}/><span className="eyebrow">LINGO ID / REWARDS</span><h2>YOUR LANE STATUS</h2><p>Connect Lingo ID to load authoritative member status, rewards, XP, and eligible offers. This shell never fabricates account state.</p><div className="statusrow"><span>ACCOUNT STATE</span><b>AUTHENTICATION REQUIRED</b></div><button className="primary" onClick={()=>setNotice('Lingo ID handoff is not configured in this repository yet.')}>CONNECT LINGO ID <ArrowRight size={17}/></button></div></main>}
  {tab==='cart'&&<main className="page narrow"><div className="pagehead"><span className="eyebrow">CART / CHECKOUT HANDOFF</span><h2>YOUR LANE CART.</h2></div>{cart.length===0?<div className="empty"><ShoppingBag size={42}/><p>Your cart is empty.</p><button className="primary" onClick={()=>setTab('shop')}>BROWSE THE LANE</button></div>:<div className="cartpanel">{cart.map(i=><div className="cartitem" key={i.key}><div><b>{i.name}</b><small>Size {i.size} • ${i.price.toFixed(2)}</small></div><div className="stepper"><button onClick={()=>qty(i.key,-1)} aria-label="Decrease"><Minus size={14}/></button><b>{i.qty}</b><button onClick={()=>qty(i.key,1)} aria-label="Increase"><Plus size={14}/></button></div></div>)}<div className="total"><span>Subtotal</span><b>${total.toFixed(2)}</b></div><button className="primary full" onClick={handoff}><Lock size={16}/> CHECKOUT HANDOFF</button><p className="fine"><Truck size={13}/> Fulfillment and payment are verified server-side when configured.</p></div>}</main>}
  <footer><span>LOYALTY LANE APPAREL™</span><span>Tap Stitch • Stay Loyal.</span><span className="desktop">No fake production success states. No client-authoritative inventory or payment.</span></footer>
 </div>}
function ProductCard({p,onAdd,onSelect}){return <article className="card"><button className="visual" onClick={()=>onSelect(p)} aria-label={'View '+p.name}><span>{p.badge}</span><Crown size={44}/><small>{p.material}</small></button><div className="cardbody"><span>{p.category}</span><h3>{p.name}</h3><p>{p.desc}</p><div className="cardfoot"><b>${p.price.toFixed(2)}</b><button className="smallbtn" onClick={()=>onAdd(p)}>ADD <Plus size={14}/></button></div></div></article>}
function ProductDetail({p,onAdd}){return <section className="detail"><div className="detailvisual"><Crown size={75}/></div><div><span className="eyebrow">PRODUCT DETAIL</span><h2>{p.name}</h2><p>{p.desc}</p><div className="sizes">{p.sizes.map(s=><button key={s} onClick={()=>onAdd(p,s)}>{s}</button>)}</div><button className="primary" onClick={()=>onAdd(p)}>ADD TO CART • ${p.price.toFixed(2)}</button></div></section>}
function ProductStrip({onAdd,onSelect}){return <section className="strip"><div><span className="eyebrow">FEATURED DROP</span><h2>Tap Stitch Essentials</h2></div><div className="stripgrid">{PRODUCTS.slice(0,3).map(p=><ProductCard key={p.id} p={p} onAdd={onAdd} onSelect={onSelect}/>)}</div></section>}
createRoot(document.getElementById('root')).render(<App/>);